[tool.poetry]
name = "papyrusai"
version = "0.1.0"
description = ""
authors = ["Wian Stipp"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^2.6.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
